### ISSUE TITLE
When will the extension offically be in marketplace

### ISSUE THREAD

**Issue by vinimehta** [aelij/vsts-service-fabric#1]
I see that the extension is currently in preview mode, is there a time when it will officially be on the visual studio marketplace?

**Comment by aelij** [comment]
As this is a self-published extension, I don't think it will ever be out of preview. From the VSTS Q&A:

> Extensions that are available during preview don't incur charges, aren't fully supported, and have no financially-backed service level agreements.

Can you explain why it matters to you?
