### ISSUE TITLE
function HashDirectory doesn't work

### ISSUE THREAD

**Issue by yurylentsevich** [aelij/vsts-service-fabric#2]
it returns the same hash codes for different xml-files. 

steps to reproduce:

1) create .xml file (>1024 bytes), save it to dir1
2) copy file to dir2 and add some nodes to the bottom
3) test HashDirectory against dir1 and dir2

**Comment by aelij** [comment]
Ah, such a silly bug! `>` instead of `-gt`...

https://github.com/aelij/vsts-service-fabric/blob/2a099a6b1cbae4a6e07e65d8aa2e02c171a6acd8/ServiceFabricPackageVersioning/Update-ServiceFabricApplicationPackageVersions.ps1#L62

Thanks for reporting this! I'll update the marketplace today.
