### ISSUE TITLE
How is it different than the "Use Diff package" option?

### ISSUE THREAD

**Issue by ThiemeNL** [aelij/vsts-service-fabric#4]
Hi, your extension looks very interesting to me. I'm planning to test/use it.

Can you explain how it is different than the "Use Diff Package" option in vsts "Deploy Service Fabric Application" task?

![image](https://user-images.githubusercontent.com/5397828/37570743-daba8bcc-2af3-11e8-8883-50447c67cba8.png)

Thanks,
Thieme

**Comment by aelij** [comment]
Hi Thieme,

First of all, this option wasn't there when I made the extension :) But it still works a bit differently than the other task. This task goes through code/config/data package versions in **all registered** app type versions. Microsoft's deploy task only checks the app type version that belongs to the **named app instance** in the current deployment. If you use multiple instances of the app, each with a different release cycle ("rings"), then this extension's strategy would work better, while Microsoft's could produce errors (such as package Code:1.0.0 already registered in the cluster).

Second, this extension also does hash-based versioning, which allows you to update only code/config/data packages that actually changed. In contrast, Microsoft's SF versioning tasks relies on build versions.

Eli.

**Comment by ThiemeNL** [comment]
Thanks for your reply! Thank you for making this available.

**Comment by Qani** [comment]
How do you configure your application when you use extensions in VSTS? How do i make it upgrade only the packages i have changed? All services get release version in the build

**Comment by aelij** [comment]
@Qani that's what "Use diff package" and the hashing is for. The task always updates the service package version, but what's important for updates are the versions of the code/config/data packages inside it.

You can read more about it in the [docs](https://docs.microsoft.com/en-us/azure/service-fabric/service-fabric-application-upgrade-advanced#upgrade-with-a-diff-package).
