### ISSUE TITLE
Which of your tasks to use?

### ISSUE THREAD

**Issue by jaymeedwards** [aelij/vsts-service-fabric#5]
Eli,

I am working on a project we took over from another vendor that uses your tasks. It currently uses the "Service Fabric package versioning" task by you, but this one gets errors with loading IdentityClient dlls and has to be hacked to work.

I noticed you have another task to do this (the one in this repo, listed on the marketplace as "Service Fabric Tools").

Which of these should I be using, and have you resolved the issues? Currently if I generate a diff package with your "old" task and include PDB files in my package (so I can get line numbers in application insights) but leave the "don't hash PDBs" option turned on, it still gets confused and thinks the package Code version has changed.

**Comment by aelij** [comment]
I'm not sure I understand. The only package I ever published is this one. Where did you get the other task? Anyway, this is the only version I maintain. I can't account for others.

As for the missing assemblies, do you mean the same issue in #3? I'm not sure what causes it. Perhaps this assembly just needs to be included with the package. What sort of "hacks" have you employed?

> it still gets confused and thinks the package Code version has changed

The task doesn't get confused, it just hashes files. I've used it successfully many times. Have you enabled deterministic builds? See the README.

**Comment by jaymeedwards** [comment]
Hey Eli,

I took over a project from another set of developers that were using a task
of yours, I thought it was different but maybe it's the same.

The "hack" the prior vendor did (and documented) was they put that
ActiveDirectory dll into a folder so it could be loaded, and they also
commented out a line where the code package was getting removed that
apparently causes diff packages to fail in ServiceFabricHelpers.ps1:


   1. open
   _tasks\ServiceFabricPackageVersioning_(GUID)\x.x\Update-ServiceFabricApplicationPackageVersions.ps1
   2. remove\comment line 114-120ish (depending on the version, 1.4.0 was
   latest):

   Remove-item $innerPackagePath -Recurse


It still seems like I get errors about code packages changing and versions
not being revved intermittently. Also if I use compression, it screws
everything up.

Jayme

**Comment by jaymeedwards** [comment]
P.S. We ARE using deterministic builds (with the appropriate compiler flag
and source map folder), but with non-portable dlls (full .NET framework).

One big problem we have, is the PDBs don't seem to be deterministic. If we
deploy them, we get hashing problems with the versioning. But then we don't
get line numbers in our log!!

Jayme
