### ISSUE TITLE
Deployment Error, Code Missing

### ISSUE THREAD

**Issue by DaveGill82** [aelij/vsts-service-fabric#7]
Hi Eli,

When upgrading an existing application I get the following error in my deployment task, after executing the versioning package...

`The BuildLayout of the application in C:\xxx\applicationpackage is invalid. Code is missing for service xxx.`

If I manually delete the application and run my pipeline it works.

Also can I use you package alongside the 'usediffpacakge' option? I know a similar question has been asked before but wondered the best way to configure the pipeline.

Thanks.

**Comment by aelij** [comment]
Sorry but I haven't touched this in years :)
